name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fritzbox-netcup-dyndns

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:$(sed 's!/!-/g' <<< ${GITHUB_REF})
